// <auto-generated />
namespace JobsAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetask));
        
        string IMigrationMetadata.Id
        {
            get { return "202005282130477_updatetask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
